### ISSUE TITLE
Error in Download Data

### ISSUE THREAD

**Issue by EDLMM** [facebookresearch/DPR#1]
Hi, I'm reproducing your work.
Before starting, a naming error for the download path occurred in the downloading script for download all the data.retriever.
This error showed:
```shell
$ python data/download_data.py --resource data.retriever
Loading from  https://dl.fbaipublicfiles.com/dpr/data/retriever/biencoder-nq-dev.json.gz
100% [......................................................................] 256239282 / 256239282Saved to  ./data/retriever/nq-dev.tmp
Uncompressing  ./data/retriever/nq-dev.tmp
Saved to  ./data/retriever/nq-dev.json
Loading from  https://dl.fbaipublicfiles.com/dpr/nq_license/LICENSE
100% [..............................................................................] 21065 / 21065Saved to  ./data/retriever/LICENSE
Loading from  https://dl.fbaipublicfiles.com/dpr/nq_license/README
100% [..................................................................................] 506 / 506Saved to  ./data/retriever/README
Loading from  https://dl.fbaipublicfiles.com/dpr/data/retriever/biencoder-nq-train.json.gz
100% [....................................................................] 2314892908 / 2314892908Saved to  ./data/retriever/nq-train.tmp
Uncompressing  ./data/retriever/nq-train.tmp
Saved to  ./data/retriever/nq-train.json
Loading from  https://dl.fbaipublicfiles.com/dpr/nq_license/LICENSE
100% [..............................................................................] 21065 / 21065Traceback (most recent call last):
  File ".../conda_env_torch1.5/lib/python3.7/shutil.py", line 566, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/data/disk1/private/liyizhi/DPR/data/retriever/LICENSEf_je2ioi.tmp' -> ' (1)./data/retriever/LICENSE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "data/download_data.py", line 348, in <module>
    main()
  File "data/download_data.py", line 340, in main
    download(args.resource, args.output_dir)
  File "data/download_data.py", line 304, in download
    download(key, out_dir)
  File "data/download_data.py", line 325, in download
    download_file(license_files[0], save_root_dir, 'LICENSE')
  File "data/download_data.py", line 294, in download_file
    wget.download(s3_url, out=local_file)
  File ".../conda_env_torch1.5/lib/python3.7/site-packages/wget.py", line 534, in download
    shutil.move(tmpfile, filename)
  File ".../conda_env_torch1.5/lib/python3.7/shutil.py", line 580, in move
    copy_function(src, real_dst)
  File ".../conda_env_torch1.5/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File ".../conda_env_torch1.5/lib/python3.7/shutil.py", line 121, in copyfile...tFoundError: [Errno 2] No such file or directory: ' (1)./data/retriever/LICENSE'
```

I've tryied some temporary change with forcing the `out_dir` fixed in `download_file` function and they were not working.

```python
def download_file(s3_url: str, out_dir: str, file_name: str):
    print('Loading from ', s3_url)
    out_dir='./data/retriever'
    local_file = os.path.join(out_dir, file_name)
    wget.download(s3_url, out=local_file)
    print('Saved to ', local_file)
```
```python
def download_file(s3_url: str, out_dir: str, file_name: str):
    print('Loading from ', s3_url)
    local_file = local_file.strip(' (1)') # this one not working
    wget.download(s3_url, out=local_file)
    print('Saved to ', local_file)
```

Finally I try to give up downloading the license and it worked.
```python
#     download_file(license_files[0], save_root_dir, 'LICENSE')
#     download_file(license_files[1], save_root_dir, 'README')
```

Hope you can figure out the bug for further usage, thanks.

**Comment by vlad-karpukhin** [comment]
Hi EDLMM,
wget is apparently not able to overwrite already downloaded files. I added a workaround, please update and check again.

Thanks,
Vlad

**Comment by EDLMM** [comment]
> Hi EDLMM,
> wget is apparently not able to overwrite already downloaded files. I added a workaround, please update and check again.
> 
> Thanks,
> Vlad

@vlad-karpukhin thanks a lot, seems that this problem disappear.
