### ISSUE TITLE
run dense_retrieval.py error

### ISSUE THREAD

**Issue by cn-boop** [facebookresearch/DPR#135]
When i run dense_retrieval.py . The following error happend.

RuntimeError: Error(s) in loading state_dict for HFBertEncoder:
        Missing key(s) in state_dict: "embeddings.position_ids". 
Could you please tell me why?

Following is the detail parameters.

[2021-04-17 16:16:40,130][root][INFO] - args.local_rank -1
[2021-04-17 16:16:40,130][root][INFO] - WORLD_SIZE None
[2021-04-17 16:16:40,293][root][INFO] - Initialized host 52ef70759d7a4852bc4e7fbfece5e87e-master-0 as d.rank -1 on device=cuda, n_gpu=8, world size=1
[2021-04-17 16:16:40,293][root][INFO] - 16-bits training: False
[2021-04-17 16:16:40,293][root][INFO] - CFG (after gpu  configuration):
[2021-04-17 16:16:40,298][root][INFO] - indexers:
  flat:
    _target_: dpr.indexer.faiss_indexers.DenseFlatIndexer
  hnsw:
    _target_: dpr.indexer.faiss_indexers.DenseHNSWFlatIndexer
  hnsw_sq:
    _target_: dpr.indexer.faiss_indexers.DenseHNSWSQIndexer
qa_dataset: nq_test
ctx_datatsets:
- dpr_wiki
encoded_ctx_files:
- /home/v-nuochen/DPR/outputs/2021-04-17/08-29-34/nq-generate-emd_0
out_file: nq_retrieval_
match: string
n_docs: 100
validation_workers: 16
batch_size: 128
do_lower_case: true
encoder_path: null
index_path: null
kilt_out_file: null
model_file: /home/v-nuochen/DPR/outputs/2021-04-15/05-14-43/nq_results/dpr_biencoder.37
validate_as_tables: false
rpc_retriever_cfg_file: null
indexer: flat
special_tokens: null
local_rank: -1
global_loss_buf_sz: 150000
device: cuda
distributed_world_size: 1
no_cuda: false
n_gpu: 8
fp16: false
fp16_opt_level: O1
encoder:
  encoder_model_type: hf_bert
  pretrained_model_cfg: bert-base-uncased
  pretrained_file: null
  projection_dim: 0
  sequence_length: 256
  dropout: 0.1
  fix_ctx_encoder: false
  pretrained: true
datasets:
  nq_test:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: data.retriever.qas.nq-test
  nq_train:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: data.retriever.qas.nq-train
  nq_dev:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: data.retriever.qas.nq-dev
  trivia_test:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: data.retriever.qas.trivia-test
  trivia_train:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: data.retriever.qas.trivia-train
  trivia_dev:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: data.retriever.qas.trivia-dev
ctx_sources:
  dpr_wiki:
    _target_: dpr.data.retriever_data.CsvCtxSrc
    file: data.wikipedia_split.psgs_w100
    id_prefix: 'wiki:'

[2021-04-17 16:16:40,305][root][INFO] - Reading saved model from /home/v-nuochen/DPR/outputs/2021-04-15/05-14-43/nq_results/dpr_biencoder.37
[2021-04-17 16:16:41,628][root][INFO] - model_state_dict keys odict_keys(['model_dict', 'optimizer_dict', 'scheduler_dict', 'offset', 'epoch', 'encoder_params'])
[2021-04-17 16:16:49,226][root][INFO] - Selecting standard question encoder
[2021-04-17 16:16:58,045][root][INFO] - Loading saved model state ...
[2021-04-17 16:16:58,046][root][INFO] - Encoder state prefix question_model.
Traceback (most recent call last):
  File "dense_retriever.py", line 459, in <module>
    main()
  File "/home/v-nuochen/.conda/envs/open/lib/python3.7/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/home/v-nuochen/.conda/envs/open/lib/python3.7/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/home/v-nuochen/.conda/envs/open/lib/python3.7/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/v-nuochen/.conda/envs/open/lib/python3.7/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()

**Comment by vlad-karpukhin** [comment]
Hi!
It is because of some non-critical mismatch between different HF transformer implementations.
You can put strict=False extra parameter when calling load_state_dict() here: 
https://github.com/facebookresearch/DPR/blob/master/dense_retriever.py#L324

I will put a fix later for this.

**Comment by vlad-karpukhin** [comment]
Just pushed a temporal fix
