### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by mynewstart** [facebookresearch/DPR#148]
Hi, when i run python dense_retriever.py model_file=/home/DPR/Result/model/dpr_biencoder.5 qa_dataset=nq_test ctx_datatsets=[dpr_wiki] encoded_ctx_files=[/home/DPR/Result/wiki_0] out_file=/*/DPR/Result/, it have the following issues. My machine have one V100(16G) and 32G memory. How much memory is required to run this model?

Traceback (most recent call last):
  File "dense_retriever.py", line 438, in main
    cfg.match,
  File "dense_retriever.py", line 193, in validate
    passages, answers, result_ctx_ids, workers_num, match_type
  File "/home/DPR/dpr/data/qa_validation.py", line 63, in calculate_matches
    processes = ProcessPool(processes=workers_num)
  File "/home/anaconda/envs/DPR/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/anaconda/envs/DPR/lib/python3.7/multiprocessing/pool.py", line 176, in __init__
    self._repopulate_pool()
  File "/home/anaconda/envs/DPR/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/home/anaconda/envs/DPR/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/anaconda/envs/DPR/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/anaconda/envs/DPR/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/anaconda/envs/DPR/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by vlad-karpukhin** [comment]
Hi,
32G is certainly not enough. I'd say you need at least 128G server to read all wikipedia & its embeddings in memory
