### ISSUE TITLE
" dpr_all_documents[doc_id]"  doc_id causing KeyError

### ISSUE THREAD

**Issue by mug2mag** [facebookresearch/DPR#153]
Hi,
I can't think of that why it has this error. I checked the codes during debugging and find that 'wiki:14419655' is large than the length of `all_passages`. I do not know why this happened. Any answer will be appreciated.
log:
[2021-05-30 23:02:58,755][root][INFO] - Reading file /home/duhuifang/git_local/DPR/downloads/data/retriever_results/n$
/single-adv-hn/wikipedia_passages_37.pkl
[2021-05-30 23:03:00,939][root][INFO] - data indexed 11350000
[2021-05-30 23:03:00,943][root][INFO] - Total data indexed 11350000
[2021-05-30 23:03:01,269][root][INFO] - data indexed 11400000
[2021-05-30 23:03:01,272][root][INFO] - Total data indexed 11400000
[2021-05-30 23:03:01,576][root][INFO] - data indexed 11450000
[2021-05-30 23:03:01,579][root][INFO] - Total data indexed 11450000
[2021-05-30 23:03:01,877][root][INFO] - data indexed 11500000
[2021-05-30 23:03:01,880][root][INFO] - Total data indexed 11500000
[2021-05-30 23:03:02,632][root][INFO] - data indexed 11550000
[2021-05-30 23:03:02,635][root][INFO] - Total data indexed 11550000
[2021-05-30 23:03:02,924][root][INFO] - data indexed 11600000
[2021-05-30 23:03:02,927][root][INFO] - Total data indexed 11600000
[2021-05-30 23:03:03,215][root][INFO] - data indexed 11650000
[2021-05-30 23:03:03,218][root][INFO] - Total data indexed 11650000
[2021-05-30 23:03:03,506][root][INFO] - data indexed 11700000
[2021-05-30 23:03:03,509][root][INFO] - Total data indexed 11700000
[2021-05-30 23:03:03,805][root][INFO] - data indexed 11750000
[2021-05-30 23:03:03,808][root][INFO] - Total data indexed 11750000
[2021-05-30 23:03:04,525][root][INFO] - data indexed 11768570
[2021-05-30 23:03:04,527][root][INFO] - Total data indexed 11768570
[2021-05-30 23:03:04,527][root][INFO] - Data indexing completed.
[2021-05-30 23:17:56,706][root][INFO] - index search time: 892.170815 sec.
[2021-05-30 23:17:56,707][dpr.data.qa_validation][INFO] - dpr_all_documents size 680788
[2021-05-30 23:18:01,835][dpr.data.qa_validation][INFO] - Matching answers in top docs...
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/python3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/duhuifang/git_local/DPR/dpr/data/qa_validation.py", line 94, in check_answer
    doc = dpr_all_documents[doc_id]
KeyError: 'wiki:14419655'

**Comment by vlad-karpukhin** [comment]
Hi @mug2mag ,
You passages set for wikipedia looks really small:
" dpr_all_documents size 680788"
 
 Our wikipedia split should have ~ 21 mln passages
 
 The same applies to the embeddings:
"Total data indexed 11768570"
You need to check if you use correct encoded_ctx_files parameter and if the downloaded tsv file for dpr_wiki actually has ~ 21 mln rows.

**Comment by mug2mag** [comment]
@vlad-karpukhin 
Thanks very much! I redownload data.wikipedia_split.psgs_w100, and the error depicted didn't emerge.
