### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by XY2323819551** [facebookresearch/DPR#160]
Hi, sorry to bother you! but I met this error when I tried to run dense_retriever.py
I could not solve it, could you help me ?
 The command line is :
python dense_retriever.py \
> model_file=/data/zhangxy/QA/DPR/dpr/data/downloads/checkpoint/retriever/single/nq/bert-base-encoder.cp \
> qa_dataset=nq_test \
> ctx_datatsets=[dpr_wiki] \
> encoded_ctx_files=[\"/data/zhangxy/QA/DPR/dpr/data/downloads/data/retriever_results/nq/single/wiki_passages_*\"] \
> out_file=/data/zhangxy/QA/DPR/dpr/nq-retriever-eval-top/

The error is as follows:
(/data/zhangxy/condenv/torch15DPR) zhangxy@gpu:/data/zhangxy/QA/DPR$ python dense_retriever.py \
> model_file=/data/zhangxy/QA/DPR/dpr/data/downloads/checkpoint/retriever/single/nq/bert-base-encoder.cp \
> qa_dataset=nq_test \
> ctx_datatsets=[dpr_wiki] \
> encoded_ctx_files=[\"/data/zhangxy/QA/DPR/dpr/data/downloads/data/retriever_results/nq/single/wiki_passages_*\"] \
> out_file=/data/zhangxy/QA/DPR/dpr/nq-retriever-eval-top/
2021-06-13 22:35:14,516 [INFO] faiss.loader: Loading faiss with AVX2 support.
2021-06-13 22:35:14,516 [INFO] faiss.loader: Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'",)
2021-06-13 22:35:14,516 [INFO] faiss.loader: Loading faiss.
2021-06-13 22:35:14,532 [INFO] faiss.loader: Successfully loaded faiss.
[2021-06-13 22:35:15,115][root][INFO] - args.local_rank -1
[2021-06-13 22:35:15,116][root][INFO] - WORLD_SIZE None
[2021-06-13 22:35:15,796][root][INFO] - Initialized host gpu as d.rank -1 on device=cuda, n_gpu=1, world size=1
[2021-06-13 22:35:15,796][root][INFO] - 16-bits training: False
[2021-06-13 22:35:15,797][root][INFO] - CFG (after gpu  configuration):
[2021-06-13 22:35:15,803][root][INFO] - indexers:
  flat:
    _target_: dpr.indexer.faiss_indexers.DenseFlatIndexer
  hnsw:
    _target_: dpr.indexer.faiss_indexers.DenseHNSWFlatIndexer
  hnsw_sq:
    _target_: dpr.indexer.faiss_indexers.DenseHNSWSQIndexer
qa_dataset: nq_test
ctx_datatsets:
- dpr_wiki
encoded_ctx_files:
- /data/zhangxy/QA/DPR/dpr/data/downloads/data/retriever_results/nq/single/wiki_passages_*
out_file: /data/zhangxy/QA/DPR/dpr/nq-retriever-eval-top/
match: string
n_docs: 100
validation_workers: 16
batch_size: 128
do_lower_case: true
encoder_path: null
index_path: null
kilt_out_file: null
model_file: /data/zhangxy/QA/DPR/dpr/data/downloads/checkpoint/retriever/single/nq/bert-base-encoder.cp
validate_as_tables: false
rpc_retriever_cfg_file: null
indexer: flat
special_tokens: null
local_rank: -1
global_loss_buf_sz: 150000
device: cuda
distributed_world_size: 1
no_cuda: false
n_gpu: 1
fp16: false
fp16_opt_level: O1
encoder:
  encoder_model_type: hf_bert
  pretrained_model_cfg: bert-base-uncased
  pretrained_file: null
  projection_dim: 0
  sequence_length: 256
  dropout: 0.1
  fix_ctx_encoder: false
  pretrained: true
datasets:
  nq_test:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: data.retriever.qas.nq-test
  nq_train:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: data.retriever.qas.nq-train
  nq_dev:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: data.retriever.qas.nq-dev
  trivia_test:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: data.retriever.qas.trivia-test
  trivia_train:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: data.retriever.qas.trivia-train
  trivia_dev:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: data.retriever.qas.trivia-dev
  webq_test:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: data.retriever.qas.webq-test
  curatedtrec_test:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: data.retriever.qas.curatedtrec-test
ctx_sources:
  dpr_wiki:
    _target_: dpr.data.retriever_data.CsvCtxSrc
    file: data.wikipedia_split.psgs_w100
    id_prefix: 'wiki:'

[2021-06-13 22:35:15,803][root][INFO] - Reading saved model from /data/zhangxy/QA/DPR/dpr/data/downloads/checkpoint/retriever/single/nq/bert-base-encoder.cp
[2021-06-13 22:35:16,311][root][INFO] - model_state_dict keys odict_keys(['model_dict', 'optimizer_dict', 'scheduler_dict', 'offset', 'epoch', 'encoder_params'])
[2021-06-13 22:35:16,317][transformers.file_utils][INFO] - PyTorch version 1.5.1 available.
[2021-06-13 22:35:17,617][transformers.configuration_utils][INFO] - loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json from cache at /home/zhangxy/.cache/torch/transformers/4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.7156163d5fdc189c3016baca0775ffce230789d7fa2a42ef516483e4ca884517
[2021-06-13 22:35:17,618][transformers.configuration_utils][INFO] - Model config BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

[2021-06-13 22:35:19,409][transformers.modeling_utils][INFO] - loading weights file https://cdn.huggingface.co/bert-base-uncased-pytorch_model.bin from cache at /home/zhangxy/.cache/torch/transformers/f2ee78bdd635b758cc0a12352586868bef80e47401abe4c4fcc3832421e7338b.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157
[2021-06-13 22:35:23,208][transformers.modeling_utils][INFO] - All model checkpoint weights were used when initializing HFBertEncoder.

[2021-06-13 22:35:23,209][transformers.modeling_utils][INFO] - All the weights of HFBertEncoder were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the ckeckpoint was trained on, you can already use HFBertEncoder for predictions without further training.
[2021-06-13 22:35:24,385][transformers.configuration_utils][INFO] - loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json from cache at /home/zhangxy/.cache/torch/transformers/4dad0251492946e18ac39290fcfe91b89d370fee250efe9521476438fe8ca185.7156163d5fdc189c3016baca0775ffce230789d7fa2a42ef516483e4ca884517
[2021-06-13 22:35:24,386][transformers.configuration_utils][INFO] - Model config BertConfig {
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

[2021-06-13 22:35:24,984][transformers.modeling_utils][INFO] - loading weights file https://cdn.huggingface.co/bert-base-uncased-pytorch_model.bin from cache at /home/zhangxy/.cache/torch/transformers/f2ee78bdd635b758cc0a12352586868bef80e47401abe4c4fcc3832421e7338b.36ca03ab34a1a5d5fa7bc3d03d55c4fa650fed07220e2eeebc06ce58d0e9a157
[2021-06-13 22:35:28,767][transformers.modeling_utils][INFO] - All model checkpoint weights were used when initializing HFBertEncoder.

[2021-06-13 22:35:28,768][transformers.modeling_utils][INFO] - All the weights of HFBertEncoder were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the ckeckpoint was trained on, you can already use HFBertEncoder for predictions without further training.
[2021-06-13 22:35:30,256][transformers.tokenization_utils_base][INFO] - loading file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /home/zhangxy/.cache/torch/transformers/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
[2021-06-13 22:35:30,310][root][INFO] - Selecting standard question encoder
[2021-06-13 22:35:31,886][root][INFO] - Loading saved model state ...
[2021-06-13 22:35:31,886][root][INFO] - Encoder state prefix question_model.
[2021-06-13 22:35:32,069][root][INFO] - Encoder vector_size=768
[2021-06-13 22:35:32,069][root][INFO] - qa_dataset: nq_test
[2021-06-13 22:35:32,094][dpr.data.download_data][INFO] - Requested resource from https://dl.fbaipublicfiles.com/dpr/data/retriever/nq-test.qa.csv
[2021-06-13 22:35:32,094][dpr.data.download_data][INFO] - Download root_dir /data/zhangxy/QA/DPR
[2021-06-13 22:35:32,095][dpr.data.download_data][INFO] - File to be downloaded as /data/zhangxy/QA/DPR/downloads/data/retriever/qas/nq-test.csv
[2021-06-13 22:35:32,095][dpr.data.download_data][INFO] - File already exist /data/zhangxy/QA/DPR/downloads/data/retriever/qas/nq-test.csv
[2021-06-13 22:35:32,095][dpr.data.download_data][INFO] - Loading from https://dl.fbaipublicfiles.com/dpr/nq_license/LICENSE
[2021-06-13 22:35:32,095][dpr.data.download_data][INFO] - File already exist /data/zhangxy/QA/DPR/downloads/data/retriever/qas/LICENSE
[2021-06-13 22:35:32,095][dpr.data.download_data][INFO] - Loading from https://dl.fbaipublicfiles.com/dpr/nq_license/README
[2021-06-13 22:35:32,095][dpr.data.download_data][INFO] - File already exist /data/zhangxy/QA/DPR/downloads/data/retriever/qas/README
[2021-06-13 22:35:32,148][root][INFO] - Index class <class 'dpr.indexer.faiss_indexers.DenseFlatIndexer'>
[2021-06-13 22:35:32,149][root][INFO] - Using special token None
[2021-06-13 22:35:55,993][root][INFO] - Encoded queries 3200
[2021-06-13 22:35:59,048][root][INFO] - Total encoded queries tensor torch.Size([3610, 768])
[2021-06-13 22:35:59,080][root][INFO] - id_prefixes per dataset: ['wiki:']
[2021-06-13 22:35:59,081][root][INFO] - ctx_files_patterns: ['/data/zhangxy/QA/DPR/dpr/data/downloads/data/retriever_results/nq/single/wiki_passages_*']
[2021-06-13 22:35:59,082][root][INFO] - Embeddings files id prefixes: []
[2021-06-13 22:35:59,082][root][INFO] - Reading all passages data from files: []
[2021-06-13 22:35:59,082][root][INFO] - Total data indexed 0
[2021-06-13 22:35:59,082][root][INFO] - Data indexing completed.
Traceback (most recent call last):
  File "dense_retriever.py", line 408, in main
    top_ids_and_scores = retriever.get_top_docs(questions_tensor.numpy(), cfg.n_docs)
  File "dense_retriever.py", line 179, in get_top_docs
    results = self.index.search_knn(query_vectors, top_docs)
  File "/data/zhangxy/QA/DPR/dpr/indexer/faiss_indexers.py", line 120, in search_knn
    for query_top_idxs in indexes
  File "/data/zhangxy/QA/DPR/dpr/indexer/faiss_indexers.py", line 120, in <listcomp>
    for query_top_idxs in indexes
  File "/data/zhangxy/QA/DPR/dpr/indexer/faiss_indexers.py", line 119, in <listcomp>
    [self.index_id_to_db_id[i] for i in query_top_idxs]
IndexError: list index out of range

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by vlad-karpukhin** [comment]
"Reading all passages data from files: []" - this means python wasn't able to find encoded_ctx_files by your glob pattern.
Can you check that your /data/zhangxy/QA/DPR/dpr/data/downloads/data/retriever_results/nq/single/wiki_passages_* path actually corresponds to wikipedia embeddings' files ?

**Comment by XY2323819551** [comment]
Thank you! I see!

**Comment by mary-octavia** [comment]
I'm having an IndexError but on a different line:

```  
File "dense_retriever.py", line 545, in main
    questions_tensor = retriever.generate_question_vectors(questions, query_token=qa_src.special_query_token)
  File "dense_retriever.py", line 128, in generate_question_vectors
    selector=self.selector,
  File "dense_retriever.py", line 75, in generate_question_vectors
    max_vector_len = max(q_t.size(1) for q_t in batch_tensors)
  File "dense_retriever.py", line 75, in <genexpr>
    max_vector_len = max(q_t.size(1) for q_t in batch_tensors)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

The command I use:
```python dense_retriever.py model_file=/data-ssd/osulea/DPR/dpr/downloads/checkpoint/retriever/single/nq/bert-base-encoder.cp qa_dataset=nq_test ctx_datatsets=[dpr_wiki] encoded_ctx_files=[\"/data-ssd/osulea/DPR/downloads/data/retriever_results/nq/single/wikipedia_passages_*\"] out_file=retr_inf.out```
