### ISSUE TITLE
A problem about  the device of "biencoder_input" in "validate_average_rank()"

### ISSUE THREAD

**Issue by yxliu-ntu** [facebookresearch/DPR#173]
Hi, all. Thank you for opening this source code.
When I execute the comment below,
```
CUDA_VISIBLE_DEVICES=0 HYDRA_FULL_ERROR=1 python train_dense_encoder.py \
    train_datasets=[curatedtrec_train] \
    dev_datasets=[curatedtrec_dev] \
    train=biencoder_local \
    output_dir=./runs/ \
    val_av_rank_start_epoch=0
```
I get the following error:
> Traceback (most recent call last):
>   File "train_dense_encoder.py", line 836, in <module>
>     main()
>   File "/home/daniel/Documents/XSL/DPR/venv/lib/python3.8/site-packages/hydra/main.py", line 49, in decorated_main
>     _run_hydra(
>   File "/home/daniel/Documents/XSL/DPR/venv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra
>     run_and_report(
>   File "/home/daniel/Documents/XSL/DPR/venv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
>     raise ex
>   File "/home/daniel/Documents/XSL/DPR/venv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
>     return func()
>   File "/home/daniel/Documents/XSL/DPR/venv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
>     lambda: hydra.run(
>   File "/home/daniel/Documents/XSL/DPR/venv/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 110, in run
>     _ = ret.return_value
>   File "/home/daniel/Documents/XSL/DPR/venv/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
>     raise self._return_value
>   File "/home/daniel/Documents/XSL/DPR/venv/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
>     ret.return_value = task_function(task_cfg)
>   File "train_dense_encoder.py", line 811, in main
>     trainer.run_train()
>   File "train_dense_encoder.py", line 206, in run_train
>     self._train_epoch(scheduler, epoch, eval_step, train_iterator)
>   File "train_dense_encoder.py", line 587, in _train_epoch
>     self.validate_and_save(
>   File "train_dense_encoder.py", line 225, in validate_and_save
>     validation_loss = self.validate_average_rank()
>   File "train_dense_encoder.py", line 395, in validate_average_rank
>     q_dense, ctx_dense = self.biencoder(
>   File "/home/daniel/Documents/XSL/DPR/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/daniel/Documents/XSL/DPR/dpr/models/biencoder.py", line 129, in forward
>     _q_seq, q_pooled_out, _q_hidden = self.get_representation(
>   File "/home/daniel/Documents/XSL/DPR/dpr/models/biencoder.py", line 104, in get_representation
>     sequence_output, pooled_output, hidden_states = sub_model(
>   File "/home/daniel/Documents/XSL/DPR/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/daniel/Documents/XSL/DPR/dpr/models/hf_models.py", line 230, in forward
>     sequence_output, pooled_output = super().forward(
>   File "/home/daniel/Documents/XSL/DPR/venv/lib/python3.8/site-packages/transformers/modeling_bert.py", line 752, in forward
>     embedding_output = self.embeddings(
>   File "/home/daniel/Documents/XSL/DPR/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/daniel/Documents/XSL/DPR/venv/lib/python3.8/site-packages/transformers/modeling_bert.py", line 178, in forward
>     inputs_embeds = self.word_embeddings(input_ids)
>   File "/home/daniel/Documents/XSL/DPR/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/daniel/Documents/XSL/DPR/venv/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
>     return F.embedding(
>   File "/home/daniel/Documents/XSL/DPR/venv/lib/python3.8/site-packages/torch/nn/functional.py", line 2043, in embedding
>     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking arugment for argument index in method wrapper_index_select)

It seems that "biencoder_input" is on "cpu" while the model is on "cuda:0", which is incompatible. 
Through adding `biencoder_input = BiEncoderBatch(**move_to_device(biencoder_input._asdict(), cfg.device))` after https://github.com/facebookresearch/DPR/blob/49e5838f94ffced8392be750ded2a8fa4a14b5cf/train_dense_encoder.py#L353-L360, this problem can be solved.

**Comment by vlad-karpukhin** [comment]
Hi @yxliu-ntu ,
I actually never tested validate_average_rank() on a single gpu, thanks for catching it.

**Comment by yxliu-ntu** [comment]
I happen to test some small data sets on a single GPU. Thanks for dealing with it.
