### ISSUE TITLE
RuntimeError: Expected object of device type cuda but got device type cpu for argument #3 'index' in call to _th_index_select

### ISSUE THREAD

**Issue by XY2323819551** [facebookresearch/DPR#178]
Hi, I am sorry to bother you! I met an issue. I want to use a subset of nq-dev-sample.json(45 samples) and nq-train-sample.json(66 samples), which is selected from nq-dev.json and nq-train.json,  to debug the training process, I rename nq-dev-sample.json(45 samples) and nq-train-sample.json(66 samples) as nq-dev.json and nq-train.json respectively，and use command "python train_dense_encoder.py train_datasets=[nq_train] dev_datasets=[nq_dev] train=biencoder_local output_dir=/data/zhangxy/QA/DPR/downloads/custom_test/retriever"to run the code, but I got the following error. how can I fix it? 
Traceback (most recent call last):
  File "train_dense_encoder.py", line 811, in main
    trainer.run_train()
  File "train_dense_encoder.py", line 206, in run_train
    self._train_epoch(scheduler, epoch, eval_step, train_iterator)
  File "train_dense_encoder.py", line 588, in _train_epoch
    epoch, train_data_iterator.get_iteration(), scheduler
  File "train_dense_encoder.py", line 225, in validate_and_save
    validation_loss = self.validate_average_rank()
  File "train_dense_encoder.py", line 403, in validate_average_rank
    representation_token_pos=rep_positions,
  File "/data/zhangxy/condenv/torch15DPR/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/zhangxy/QA/DPR/dpr/models/biencoder.py", line 135, in forward
    representation_token_pos=representation_token_pos,
  File "/data/zhangxy/QA/DPR/dpr/models/biencoder.py", line 108, in get_representation
    representation_token_pos=representation_token_pos,
  File "/data/zhangxy/condenv/torch15DPR/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/zhangxy/QA/DPR/dpr/models/hf_models.py", line 232, in forward
    attention_mask=attention_mask,
  File "/data/zhangxy/condenv/torch15DPR/lib/python3.6/site-packages/transformers/modeling_bert.py", line 753, in forward
    input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds
  File "/data/zhangxy/condenv/torch15DPR/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/zhangxy/condenv/torch15DPR/lib/python3.6/site-packages/transformers/modeling_bert.py", line 178, in forward
    inputs_embeds = self.word_embeddings(input_ids)
  File "/data/zhangxy/condenv/torch15DPR/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/zhangxy/condenv/torch15DPR/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/data/zhangxy/condenv/torch15DPR/lib/python3.6/site-packages/torch/nn/functional.py", line 1724, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected object of device type cuda but got device type cpu for argument #3 'index' in call to _th_index_select

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by XY2323819551** [comment]
And I dont know how to analyze the Traceback info 😂…

**Comment by vlad-karpukhin** [comment]
train_dense_encoder is supposed to be used in DDP mode, even if you have just 2 gpus (but at least 8 required to make it effective). Please have a look at our instructions on how to use 'torch.distributed.launch' tp run it in DDP mode

**Comment by XY2323819551** [comment]
> train_dense_encoder is supposed to be used in DDP mode, even if you have just 2 gpus (but at least 8 required to make it effective). Please have a look at our instructions on how to use 'torch.distributed.launch' tp run it in DDP mode

Thank you very much !
