### ISSUE TITLE
Problem with multi-gpu training

### ISSUE THREAD

**Issue by jigsaw2212** [facebookresearch/DPR#192]
Hi,

I'm trying to finetune a DPR checkpoint on my own dataset. While it works perfectly on a single GPU, I get the following error while attempting multi-gpu training:

`TypeError: forward() missing 6 required positional arguments: 'question_ids', 'question_segments', 'question_attn_mask', 'context_ids', 'ctx_segments', and 'ctx_attn_mask'`

Any pointers on how to resolve this on a multi-gpu setting?

**Comment by vlad-karpukhin** [comment]
Hi @jigsaw2212 ,
Can you post here your full log output ?

**Comment by unw9527** [comment]
Hi @vlad-karpukhin , I have the similar issue when I want to train the retriever on my own dataset. Namely, I created train_data.json and dev_data.json for training, and I just followed the format specified in README as follows:
```
[
  {
	"question": "....",
	"answers": ["...", "...", "..."],
	"positive_ctxs": [{
		"title": "...",
		"text": "...."
	}],
	"negative_ctxs": ["..."],
	"hard_negative_ctxs": ["..."]
  },
  ...
]
```

And the full log is here:

```
[140702554421056] 2021-10-19 00:55:18,348 [INFO] root: Sys.argv: ['train_dense_encoder.py', 'train_datasets=[train_data]', 'dev_datasets=[dev_data]', 'train=biencoder_local', 'output_dir=./outputs']
[140702554421056] 2021-10-19 00:55:18,348 [INFO] root: Hydra formatted Sys.argv: ['train_dense_encoder.py', 'train_datasets=[train_data]', 'dev_datasets=[dev_data]', 'train=biencoder_local', 'output_dir=./outputs']
/home/xxx/anaconda3/envs/keyword/lib/python3.7/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'biencoder_train_cfg': Defaults list is missing `_self_`. See https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/home/xxx/anaconda3/envs/keyword/lib/python3.7/site-packages/hydra/core/default_element.py:126: UserWarning: In 'datasets/encoder_train_default': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  See {url} for more information"""
/home/xxx/anaconda3/envs/keyword/lib/python3.7/site-packages/hydra/core/default_element.py:126: UserWarning: In 'train/biencoder_local': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  See {url} for more information"""
/home/xxx/anaconda3/envs/keyword/lib/python3.7/site-packages/hydra/core/default_element.py:126: UserWarning: In 'encoder/hf_bert': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_package_header for more information
  See {url} for more information"""
[2021-10-19 00:55:18,643][root][INFO] - args.local_rank -1
[2021-10-19 00:55:18,644][root][INFO] - WORLD_SIZE None
[2021-10-19 00:55:18,754][root][INFO] - Initialized host owl2 as d.rank -1 on device=cuda, n_gpu=3, world size=1
[2021-10-19 00:55:18,755][root][INFO] - 16-bits training: False 
[2021-10-19 00:55:18,759][root][INFO] - CFG (after gpu  configuration):
[2021-10-19 00:55:18,766][root][INFO] - encoder:
  encoder_model_type: hf_bert
  pretrained_model_cfg: bert-base-uncased
  pretrained_file: null
  projection_dim: 0
  sequence_length: 256
  dropout: 0.1
  fix_ctx_encoder: false
  pretrained: true
train:
  batch_size: 4
  dev_batch_size: 16
  adam_eps: 1.0e-08
  adam_betas: (0.9, 0.999)
  max_grad_norm: 2.0
  log_batch_step: 1
  train_rolling_loss_step: 100
  weight_decay: 0.0
  learning_rate: 2.0e-05
  warmup_steps: 1237
  gradient_accumulation_steps: 1
  num_train_epochs: 40
  eval_per_epoch: 1
  hard_negatives: 1
  other_negatives: 0
  val_av_rank_hard_neg: 30
  val_av_rank_other_neg: 30
  val_av_rank_bsz: 128
  val_av_rank_max_qs: 10000
datasets:
  nq_train:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: data.retriever.nq-train
  nq_train_hn1:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: data.retriever.nq-adv-hn-train
  nq_dev:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: data.retriever.nq-dev
  trivia_train:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: data.retriever.trivia-train
  trivia_dev:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: data.retriever.trivia-dev
  squad1_train:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: data.retriever.squad1-train
  squad1_dev:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: data.retriever.squad1-dev
  webq_train:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: data.retriever.webq-train
  webq_dev:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: data.retriever.webq-dev
  curatedtrec_train:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: data.retriever.curatedtrec-train
  curatedtrec_dev:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: data.retriever.curatedtrec-dev
  train_data:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: data.retriever.train_data
  dev_data:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: data.retriever.dev_data
train_datasets:
- train_data
dev_datasets:
- dev_data
output_dir: ./outputs
train_sampling_rates: null
loss_scale_factors: null
do_lower_case: true
fix_ctx_encoder: false
val_av_rank_start_epoch: 30
seed: 12345
checkpoint_file_name: dpr_biencoder
model_file: null
local_rank: -1
global_loss_buf_sz: 592000
device: cuda
distributed_world_size: 1
distributed_port: null
no_cuda: false
n_gpu: 3
fp16: false
fp16_opt_level: O1
special_tokens: null
ignore_checkpoint_offset: false
ignore_checkpoint_optimizer: false
multi_q_encoder: false

[2021-10-19 00:55:18,767][root][INFO] - ***** Initializing components for training *****
[2021-10-19 00:55:18,767][root][INFO] - Checkpoint files []
[2021-10-19 00:55:32,321][dpr.utils.conf_utils][INFO] - train_datasets: ['train_data']
[2021-10-19 00:55:32,323][dpr.data.biencoder_data][INFO] - Data files: []
[2021-10-19 00:55:32,323][dpr.utils.conf_utils][INFO] - dev_datasets: ['dev_data']
[2021-10-19 00:55:32,324][dpr.data.biencoder_data][INFO] - Data files: []
[2021-10-19 00:55:32,324][root][INFO] - Initializing task/set data ['train_data']
[2021-10-19 00:55:32,327][dpr.data.download_data][INFO] - Requested resource from https://dl.fbaipublicfiles.com/dpr/data/retriever/biencoder-nq-dev.json.gz
[2021-10-19 00:55:32,327][dpr.data.download_data][INFO] - Download root_dir /scratch/xxx/DPR
[2021-10-19 00:55:32,327][dpr.data.download_data][INFO] - File to be downloaded as /scratch/xxx/DPR/downloads/data/retriever/train_data.json
[2021-10-19 00:55:32,327][dpr.data.download_data][INFO] - File already exist /scratch/xxx/DPR/downloads/data/retriever/train_data.json
[2021-10-19 00:55:32,327][root][INFO] - Reading file /scratch/xxx/DPR/downloads/data/retriever/train_data.json
[2021-10-19 00:55:32,731][root][INFO] - Aggregated data size: 1074
[2021-10-19 00:55:32,731][dpr.data.biencoder_data][INFO] - Total cleaned data size: 1074
[2021-10-19 00:55:32,731][root][INFO] - samples_per_shard=1074, shard_start_idx=0, shard_end_idx=1074, max_iterations=268
[2021-10-19 00:55:32,732][root][INFO] - rank=-1; Multi set data sizes [1074]
[2021-10-19 00:55:32,732][root][INFO] - rank=-1; Multi set total data 1074
[2021-10-19 00:55:32,732][root][INFO] - rank=-1; Multi set sampling_rates None
[2021-10-19 00:55:32,732][root][INFO] - rank=-1; Multi set max_iterations per dataset [268]
[2021-10-19 00:55:32,732][root][INFO] - rank=-1; Multi set max_iterations 268
[2021-10-19 00:55:32,732][root][INFO] -   Total iterations per epoch=268
[2021-10-19 00:55:32,732][root][INFO] -  Total updates=10720
[2021-10-19 00:55:32,732][root][INFO] -   Eval step = 268
[2021-10-19 00:55:32,732][root][INFO] - ***** Training *****
[2021-10-19 00:55:32,733][root][INFO] - ***** Epoch 0 *****
[2021-10-19 00:55:32,734][root][INFO] - rank=-1; Iteration start
[2021-10-19 00:55:32,734][root][INFO] - rank=-1; Multi set iteration: iteration ptr per set: [0]
[2021-10-19 00:55:32,734][root][INFO] - rank=-1; Multi set iteration: source 0, batches to be taken: 268
[2021-10-19 00:55:32,735][root][INFO] - rank=-1; data_src_indices len=268
Error executing job with overrides: ['train_datasets=[train_data]', 'dev_datasets=[dev_data]', 'train=biencoder_local', 'output_dir=./outputs']
Traceback (most recent call last):
  File "train_dense_encoder.py", line 758, in main
    trainer.run_train()
  File "train_dense_encoder.py", line 196, in run_train
    self._train_epoch(scheduler, epoch, eval_step, train_iterator)
  File "train_dense_encoder.py", line 493, in _train_epoch
    loss_scale=loss_scale,
  File "train_dense_encoder.py", line 698, in _do_biencoder_fwd_pass
    representation_token_pos=rep_positions,
  File "/home/xxx/anaconda3/envs/keyword/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xxx/anaconda3/envs/keyword/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/xxx/anaconda3/envs/keyword/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/xxx/anaconda3/envs/keyword/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/xxx/anaconda3/envs/keyword/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 2 on device 2.
Original Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/keyword/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/xxx/anaconda3/envs/keyword/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 6 required positional arguments: 'question_ids', 'question_segments', 'question_attn_mask', 'context_ids', 'ctx_segments', and 'ctx_attn_mask'
```

I wonder how I can fix this bug. Thanks.
