### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by Suki-m730026038** [facebookresearch/DPR#198]
Hi Vlad, when I try to run  train_dense_encoder.py with following code:
python train_dense_encoder.py train_datasets=[nq_train] dev_datasets=[nq_dev] train=biencoder_local
it occur the TypeError, which shows below:
Error executing job with overrides: ['train_datasets=[nq_train]', 'dev_datasets=[nq_dev]', 'train=biencoder_local']
Traceback (most recent call last):
  File "train_dense_encoder.py", line 758, in main
    trainer.run_train()
  File "train_dense_encoder.py", line 196, in run_train
    self._train_epoch(scheduler, epoch, eval_step, train_iterator)
  File "train_dense_encoder.py", line 493, in _train_epoch
    loss_scale=loss_scale,
  File "train_dense_encoder.py", line 698, in _do_biencoder_fwd_pass
    representation_token_pos=rep_positions,
  File "/research/dept8/msc/yqlai21/anaconda3/envs/cuhk/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/research/dept8/msc/yqlai21/DPR-main/dpr/models/biencoder.py", line 131, in forward
    representation_token_pos=representation_token_pos,
  File "/research/dept8/msc/yqlai21/DPR-main/dpr/models/biencoder.py", line 108, in get_representation
    representation_token_pos=representation_token_pos,
  File "/research/dept8/msc/yqlai21/anaconda3/envs/cuhk/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/research/dept8/msc/yqlai21/DPR-main/dpr/models/hf_models.py", line 211, in forward
    pooled_output = sequence_output[:, representation_token_pos, :]
TypeError: string indices must be integers
I already download the code and dataset and all the package. Can you help me to solve this problem?

**Comment by vlad-karpukhin** [comment]
Hi @Suki-m730026038 ,
Looks like you modified the code.
The error line above is 207 not 211 like in your stack above:
https://github.com/facebookresearch/DPR/blob/1ee31c6c5335f05c45138161eb5ce2c03023115d/dpr/models/hf_models.py#L207

representation_token_pos should int which is guarder by isinstance() check in my code so that the error above should never happen unless you changed something.
You need to find out what your  representation_token_pos is in that method, please place the log message at the beginnig of the method and let me know what you have changed.

 representation_token_pos is an int or a tensor of indexes from which position to take the entire passage representation.
0 is a standard option for BERT as it takes the representation from CLS token.
