### ISSUE TITLE
Retriever Training Error with train_dense_encoder.py

### ISSUE THREAD

**Issue by AIML-YOGI** [facebookresearch/DPR#220]
Getting the below error any ideas?

**Running on T4 Linux -**
$ python train_dense_encoder.py \ train_datasets=[nq_train] \ dev_datasets=[nq_dev] \ train=biencoder_local

Log
2022-06-03 17:05:29.993413: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
train_dense_encoder.py:747: UserWarning:
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="conf", config_name="biencoder_train_cfg")
[140158170493888] 2022-06-03 17:05:31,592 [INFO] root: Sys.argv: ['train_dense_encoder.py', ' train_datasets=[nq_train]', ' dev_datasets=[nq_dev]', ' train=biencoder_local']
[140158170493888] 2022-06-03 17:05:31,594 [INFO] root: Hydra formatted Sys.argv: ['train_dense_encoder.py', ' train_datasets=[nq_train]', ' dev_datasets=[nq_dev]', ' train=biencoder_local']

Traceback (most recent call last):
  File "train_dense_encoder.py", line 790, in <module>
    main()
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/hydra/_internal/utils.py", line 389, in _run_hydra
    _run_app(
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/hydra/_internal/utils.py", line 452, in _run_app
    run_and_report(
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/hydra/_internal/utils.py", line 216, in run_and_report
    raise ex
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 105, in run
    cfg = self.compose_config(
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 594, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 141, in load_configuration
    return self._load_configuration_impl(
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 233, in _load_configuration_impl
    parsed_overrides = parser.parse_overrides(overrides=overrides)
  File "/anaconda/envs/py38_default/lib/python3.8/site-packages/hydra/core/override_parser/overrides_parser.py", line 96, in parse_overrides
    raise OverrideParseException(
hydra.errors.OverrideParseException: LexerNoViableAltException:  train_datasets=[nq_train]

**Comment by AIML-YOGI** [comment]
Forgot to add 1 additional line - 
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details
