### ISSUE TITLE
retriver bugs:pickle.load()  ValueError: could not convert string to int

### ISSUE THREAD

**Issue by shanekong** [facebookresearch/DPR#51]
Reading file /storage03/users/nq_open/retriver/DPR/dpr_ctx_10
Reading file /storage03/users//nq_open/retriver/DPR/dpr_ctx.index.dpr
Traceback (most recent call last):
  File "dense_retriever.py", line 303, in <module>
    main(args)
  File "dense_retriever.py", line 242, in main
    retriever.index_encoded_data(input_paths, buffer_size=index_buffer_sz)
  File "dense_retriever.py", line 92, in index_encoded_data
    for i, item in enumerate(iterate_encoded_files(vector_files)):
  File "dense_retriever.py", line 193, in iterate_encoded_files
    doc_vectors = pickle.load(reader)
ValueError: could not convert string to int

**Comment by shanekong** [comment]
caused by other files such as dpr_ctx.index.dpr; this is the tmp files. 
params likes --encoded_ctx_file ${base_dir}/'dpr_ctx*'  should be fed a fixed value.
