### ISSUE TITLE
dpr_all_documents is not defined

### ISSUE THREAD

**Issue by ramybaly** [facebookresearch/DPR#52]
I am encountering the error of  "dpr_all_documents is not defined"  when running the dense_retriever.py script, particularly at the "validate" function right before saving the results.

**Comment by vlad-karpukhin** [comment]
Hi Ramy,
Can you post your exact command and the entire log?

**Comment by vlad-karpukhin** [comment]
Closing since no details provided.

**Comment by mug2mag** [comment]
@vlad-karpukhin  I also got this error. 
Command: 
`
python dense_retriever.py model_file=DPR/downloads/checkpoint/retriever/single-adv-hn/nq/bert-base-encoder.cp qa_dataset=nq_test encoded_ctx_files=[\"DPR/downloads/data/retriever_results/nq/single-adv-hn/wikipedia_passages_*\"] ctx_datatsets=[dpr_wiki] out_file=DPR/downloads/evaluation`
Log:
2021-05-21 09:31:20,609 [INFO] faiss.loader: Loading faiss with AVX2 support.
2021-05-21 09:31:20,609 [INFO] faiss.loader: Loading faiss with AVX2 support.
2021-05-21 09:31:20,610 [INFO] faiss.loader: Loading faiss.
2021-05-21 09:31:20,610 [INFO] faiss.loader: Loading faiss.
2021-05-21 09:31:20,610 [INFO] faiss.loader: Loading faiss with AVX2 support.
2021-05-21 09:31:20,610 [INFO] faiss.loader: Loading faiss with AVX2 support.
2021-05-21 09:31:20,610 [INFO] faiss.loader: Loading faiss.
2021-05-21 09:31:20,610 [INFO] faiss.loader: Loading faiss.
2021-05-21 09:31:20,611 [INFO] faiss.loader: Loading faiss with AVX2 support.
2021-05-21 09:31:20,612 [INFO] faiss.loader: Loading faiss.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/duhuifang/git_local/DPR/dpr/data/qa_validation.py", line 94, in check_answer
    doc = dpr_all_documents[doc_id]
NameError: name 'dpr_all_documents' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dense_retriever.py", line 438, in main
    cfg.match,
  File "dense_retriever.py", line 193, in validate
    passages, answers, result_ctx_ids, workers_num, match_type
  File "/home/duhuifang/git_local/DPR/dpr/data/qa_validation.py", line 72, in calculate_matches
    scores = processes.map(get_score_partial, questions_answers_docs)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
NameError: name 'dpr_all_documents' is not defined

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by vlad-karpukhin** [comment]
Hi @mug2mag ,
Can you provide the full log?
Specifically, is there a line with 'dpr_all_documents size '
Also, can you check that wikipedia passages tsv file was downloaded ?

**Comment by mug2mag** [comment]
**full log**:
[2021-05-21 08:58:51,501][root][INFO] - Reading file /home/duhuifang/git_local/DPR/downloads/data/retriever_results/nq/│
single-adv-hn/wikipedia_passages_49.pkl                                                                                
[2021-05-21 08:58:56,517][root][INFO] - data indexed 20600000                                                          
[2021-05-21 08:58:56,517][root][INFO] - Total data indexed 20600000                                                    
[2021-05-21 08:58:57,015][root][INFO] - data indexed 20650000                                                          
[2021-05-21 08:58:57,015][root][INFO] - Total data indexed 20650000                                                    
[2021-05-21 08:58:58,101][root][INFO] - data indexed 20700000                                                          
[2021-05-21 08:58:58,102][root][INFO] - Total data indexed 20700000                                                    
[2021-05-21 08:58:58,556][root][INFO] - data indexed 20750000                                                          
[2021-05-21 08:58:58,557][root][INFO] - Total data indexed 20750000                                                    
[2021-05-21 08:58:59,646][root][INFO] - data indexed 20800000                                                          
[2021-05-21 08:58:59,646][root][INFO] - Total data indexed 20800000                                                    
[2021-05-21 08:59:00,079][root][INFO] - data indexed 20850000                                                          
[2021-05-21 08:59:00,080][root][INFO] - Total data indexed 20850000                                                    
[2021-05-21 08:59:01,168][root][INFO] - data indexed 20900000                                                          
[2021-05-21 08:59:01,169][root][INFO] - Total data indexed 20900000                                                    
[2021-05-21 08:59:01,613][root][INFO] - data indexed 20950000                                                          
[2021-05-21 08:59:01,614][root][INFO] - Total data indexed 20950000                                                    
[2021-05-21 08:59:02,685][root][INFO] - data indexed 21000000                                                          
[2021-05-21 08:59:02,685][root][INFO] - Total data indexed 21000000                                                    
[2021-05-21 08:59:03,040][root][INFO] - data indexed 21015324                                                          
[2021-05-21 08:59:03,040][root][INFO] - Total data indexed 21015324                                                    
[2021-05-21 08:59:03,040][root][INFO] - Data indexing completed.                                                       
[2021-05-21 09:26:47,548][root][INFO] - index search time: 1664.477587 sec.                                            
[2021-05-21 09:26:47,551][dpr.data.download_data][INFO] - Requested resource from https://dl.fbaipublicfiles.com/dpr/wi│
kipedia_split/psgs_w100.tsv.gz                                                                                         
[2021-05-21 09:26:47,551][dpr.data.download_data][INFO] - Download root_dir /home/duhuifang/git_local/DPR              
[2021-05-21 09:26:47,551][dpr.data.download_data][INFO] - File to be downloaded as /home/duhuifang/git_local/DPR/downlo│
ads/data/wikipedia_split/psgs_w100.tsv                                                                                 
[2021-05-21 09:26:47,551][dpr.data.download_data][INFO] - File already exist /home/duhuifang/git_local/DPR/downloads/da│
ta/wikipedia_split/psgs_w100.tsv                                                                                       
[2021-05-21 09:31:06,786][dpr.data.qa_validation][INFO] - dpr_all_documents size 21015324                              
The current process just got forked. Disabling parallelism to avoid deadlocks...                                       
To disable this warning, please explicitly set TOKENIZERS_PARALLELISM=(true | false)                                   
The current process just got forked. Disabling parallelism to avoid deadlocks...                                       
To disable this warning, please explicitly set TOKENIZERS_PARALLELISM=(true | false)                                   
[2021-05-21 09:31:11,693][dpr.data.qa_validation][INFO] - Matching answers in top docs...                              
2021-05-21 09:31:20,607 [INFO] faiss.loader: Loading faiss with AVX2 support.                                          
2021-05-21 09:31:20,608 [INFO] faiss.loader: Loading faiss.                                                            
2021-05-21 09:31:20,608 [INFO] faiss.loader: Loading faiss with AVX2 support.                                          
2021-05-21 09:31:20,609 [INFO] faiss.loader: Loading faiss.                                                            
2021-05-21 09:31:20,608 [INFO] faiss.loader: Loading faiss with AVX2 support.                                          
2021-05-21 09:31:20,609 [INFO] faiss.loader: Loading faiss.                                                            
2021-05-21 09:31:20,609 [INFO] faiss.loader: Loading faiss with AVX2 support.                                          
2021-05-21 09:31:20,609 [INFO] faiss.loader: Loading faiss with AVX2 support.                                          
2021-05-21 09:31:20,610 [INFO] faiss.loader: Loading faiss.                                                            
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
result = (True, func(*args, **kwds))
File "/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
return list(map(*args))
File "/home/duhuifang/git_local/DPR/dpr/data/qa_validation.py", line 94, in check_answer
doc = dpr_all_documents[doc_id]
NameError: name 'dpr_all_documents' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "dense_retriever.py", line 438, in main
cfg.match,
File "dense_retriever.py", line 193, in validate
passages, answers, result_ctx_ids, workers_num, match_type
File "/home/duhuifang/git_local/DPR/dpr/data/qa_validation.py", line 72, in calculate_matches
scores = processes.map(get_score_partial, questions_answers_docs)
File "/usr/lib64/python3.6/multiprocessing/pool.py", line 266, in map
return self._map_async(func, iterable, mapstar, chunksize).get()
File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
raise self._value
NameError: name 'dpr_all_documents' is not defined

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```


Yes,   there is a line with 'dpr_all_documents size ' like `logger.info("dpr_all_documents size %d", len(dpr_all_documents))`;
And I have downloaded the wikipedia passages tsv file.

**Comment by vlad-karpukhin** [comment]
ok, so your passages set downloaded successfully in python code, 
Then your python can't see the global variable dpr_all_documents which is defined in calculate_matches()

Comparing your log with mine I don't see I ever had this: 
"The current process just got forked. Disabling parallelism to avoid deadlocks... "

Looks like your validation threads forked in a different way vs mine and thus they don't see global variable. 
ProcessPool initializes with "fork" multiprocessing part by default on unix.
But I had no issue like this before.

The messages comes from HF tokenizers.
Can you try to play with TOKENIZERS_PARALLELISM=false|true env variable like described here:
https://stackoverflow.com/questions/62691279/how-to-disable-tokenizers-parallelism-true-false-warning

**Comment by mug2mag** [comment]
@vlad-karpukhin Thanks very much. It works for me!
