### ISSUE TITLE
Question in "reader model input data pre-processing"

### ISSUE THREAD

**Issue by ReyonRen** [facebookresearch/DPR#67]
Hi, thanks for you sharing!

When I run `preprocess_reader_data.py`, after split data into 16 chunks, I was returned a error infomation called: 

```
Traceback (most recent call last):
  File "//mnt/dqa/lihongyu04/python3.7_torch1.1/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "//mnt/dqa/lihongyu04/python3.7_torch1.1/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/mnt/dqa/renruiyang/env/DPR/dpr/data/reader_data.py", line 425, in _preprocess_reader_samples_chunk
    for i, r in enumerate(iterator):
  File "//mnt/dqa/lihongyu04/python3.7_torch1.1/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "/mnt/dqa/renruiyang/env/DPR/dpr/data/reader_data.py", line 152, in preprocess_retriever_data
    is_train_set,
  File "/mnt/dqa/renruiyang/env/DPR/dpr/data/reader_data.py", line 280, in _select_reader_passages
    answers_token_ids = [tensorizer.text_to_tensor(a, add_special_tokens=False) for a in answers]
  File "/mnt/dqa/renruiyang/env/DPR/dpr/data/reader_data.py", line 280, in <listcomp>
    answers_token_ids = [tensorizer.text_to_tensor(a, add_special_tokens=False) for a in answers]
  File "/mnt/dqa/renruiyang/env/DPR/dpr/models/hf_models.py", line 154, in text_to_tensor
    pad_to_max_length=False, truncation=True)
  File "//mnt/dqa/lihongyu04/python3.7_torch1.1/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 816, in encode
    **kwargs,
  File "//mnt/dqa/lihongyu04/python3.7_torch1.1/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 908, in encode_plus
    first_ids = get_input_ids(text)
  File "//mnt/dqa/lihongyu04/python3.7_torch1.1/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 898, in get_input_ids
    return self.convert_tokens_to_ids(self.tokenize(text, **kwargs))

▽
  File "//mnt/dqa/lihongyu04/python3.7_torch1.1/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 723, in tokenize
    tokenized_text = split_on_tokens(added_tokens, text)
  File "//mnt/dqa/lihongyu04/python3.7_torch1.1/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 717, in split_on_tokens
    for token in tokenized_text
  File "//mnt/dqa/lihongyu04/python3.7_torch1.1/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 717, in <genexpr>
    for token in tokenized_text
TypeError: _tokenize() got an unexpected keyword argument 'truncation'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/preprocess_reader_data.py", line 49, in <module>
    main(args)
  File "src/preprocess_reader_data.py", line 28, in main
    tensorizer, args.num_workers)
  File "/mnt/dqa/renruiyang/env/DPR/dpr/data/reader_data.py", line 215, in convert_retriever_results
    for file_name in workers.map(_parse_batch, chunks):
  File "//mnt/dqa/lihongyu04/python3.7_torch1.1/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "//mnt/dqa/lihongyu04/python3.7_torch1.1/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
TypeError: _tokenize() got an unexpected keyword argument 'truncation'
```

My settings are:
```
python src/preprocess_reader_data.py \
        --retriever_results ./official-reproduce/nq-train.json \
        --gold_passages_src ./official-reproduce/nq-train_gold_info.json \
        --do_lower_case \
        --pretrained_model_cfg bert-base-uncased \
        --encoder_model_type hf_bert \
        --out_file ./ \
       --is_train_set
```

Please help me solve this bug...
Thank you!

**Comment by ReyonRen** [comment]
It seems like the problem is located in multiprocessing pool?

**Comment by ReyonRen** [comment]
I deleted `truncation=True` from
`token_ids = self.tokenizer.encode(title, text_pair=text, add_special_tokens=add_special_tokens, max_length=self.max_length, pad_to_max_length=False, truncation=True)`
Now the code runs successfully, I wonder if my method is right?

**Comment by MFajcik** [comment]
@ReyonRen what version of transformers are you using? If I remember correctly, truncation argument was added somewhere around transformers 3.0.X version? 

Therefore you are probably using a different version of transformers than the original code did.

**Comment by ReyonRen** [comment]
> @ReyonRen what version of transformers are you using? If I remember correctly, truncation argument was added somewhere around transformers 3.0.X version?
> 
> Therefore you are probably using a different version of transformers than the original code did.

Thank you! I'll check it.

**Comment by vlad-karpukhin** [comment]
As Martin correctly mentioned, we added truncation for HF tokenizer initialization to avoid swarming log output for HF versions>=3.0. 
But we also needed to update setup HF version, which we forgot to do.

**Comment by ReyonRen** [comment]
@vlad-karpukhin Thank you!
